language: generic 

sudo: required
services: 
  - docker

before_install:
  - docker build -t argoebel/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true argoebel/docker-react-demo npm run test -- --coverage