language: generic 

sudo: required
services: 
  - docker

before_install:
  - docker build -t argoebel/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true argoebel/docker-react-demo npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react-demo"
  env: "Dockerreactdemo-env"
  bucket_name: "elasticbeanstalk-ca-central-1-088370988199"
  bucket_path: "docker"
  on:
    branch: master
    
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY